apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue

spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: nginx

    spec:
      containers:
        - name: nginx
          image: nginx 

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In
                  values:
                    - blue
      